import airpods from './assets/images/airpods.jpeg'
import airpodss from './assets/images/airpods.jpg'
const products = [
    {
        _id: '1',
        name: 'Airpods Wireless Bluetooth Headphones',
        image: airpodss,
        description: `AirPods Pro (2nd generation) with USB-C deliver up to 2x more Active Noise Cancellation than the previous generation, with Transparency mode that enables you to hear the world around you, and all-new Adaptive Audio that dynamically tailors noise control to your environment. Conversation Awareness helps lower media volume and enhance the voices in front of you while youre interacting with others. A single charge delivers up to 6 hours of battery life. And Touch control lets you easily adjust volume with a swipe. The MagSafe Charging Case is a marvel on its own with Precision Finding, built-in speaker and lanyard loop.`,
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStocks: 0,
        rating: 4.5,
        numReviews: 12,
    },
    {
        _id: '2',
        name: 'Apple iPhone 15',
        image: airpods,
        description: `Experience the iPhone 15 – your dynamic companion. Dynamic Island ensures you stay connected, bubbling up alerts seamlessly while you're busy. Its durable design features infused glass and aerospace-grade aluminum, making it dependable and resistant to water and dust. Capture life with precision using the 48 MP Main Camera, perfect for any shot. Powered by the A16 Bionic Processor, it excels in computational photography and more, all while conserving battery life. Plus, it's USB-C compatible, simplifying your charging needs. Elevate your tech game with the iPhone 15 – innovation at your fingertips. Goodbye cable clutter, hello convenience.`,
        brand: 'Apple',
        category: 'Electronics',
        price: 679.99,
        countInStocks: 20,
        rating: 4.9,
        numReviews: 120,
    },
    {
        _id: '2',
        name: 'Apple iPhone 15',
        image: airpods,
        description: `Experience the iPhone 15 – your dynamic companion. Dynamic Island ensures you stay connected, bubbling up alerts seamlessly while you're busy. Its durable design features infused glass and aerospace-grade aluminum, making it dependable and resistant to water and dust. Capture life with precision using the 48 MP Main Camera, perfect for any shot. Powered by the A16 Bionic Processor, it excels in computational photography and more, all while conserving battery life. Plus, it's USB-C compatible, simplifying your charging needs. Elevate your tech game with the iPhone 15 – innovation at your fingertips. Goodbye cable clutter, hello convenience.`,
        brand: 'Apple',
        category: 'Electronics',
        price: 679.99,
        countInStocks: 20,
        rating: 4.9,
        numReviews: 120,
    },
    {
        _id: '2',
        name: 'Apple iPhone 15',
        image: airpods,
        description: `Experience the iPhone 15 – your dynamic companion. Dynamic Island ensures you stay connected, bubbling up alerts seamlessly while you're busy. Its durable design features infused glass and aerospace-grade aluminum, making it dependable and resistant to water and dust. Capture life with precision using the 48 MP Main Camera, perfect for any shot. Powered by the A16 Bionic Processor, it excels in computational photography and more, all while conserving battery life. Plus, it's USB-C compatible, simplifying your charging needs. Elevate your tech game with the iPhone 15 – innovation at your fingertips. Goodbye cable clutter, hello convenience.`,
        brand: 'Apple',
        category: 'Electronics',
        price: 679.99,
        countInStocks: 20,
        rating: 4.9,
        numReviews: 120,
    },
    {
        _id: '2',
        name: 'Apple iPhone 15',
        image: airpods,
        description: `Experience the iPhone 15 – your dynamic companion. Dynamic Island ensures you stay connected, bubbling up alerts seamlessly while you're busy. Its durable design features infused glass and aerospace-grade aluminum, making it dependable and resistant to water and dust. Capture life with precision using the 48 MP Main Camera, perfect for any shot. Powered by the A16 Bionic Processor, it excels in computational photography and more, all while conserving battery life. Plus, it's USB-C compatible, simplifying your charging needs. Elevate your tech game with the iPhone 15 – innovation at your fingertips. Goodbye cable clutter, hello convenience.`,
        brand: 'Apple',
        category: 'Electronics',
        price: 679.99,
        countInStocks: 20,
        rating: 4.9,
        numReviews: 120,
    },
]

export default products 